/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lecture_one_jninative_HelloJNI */

#ifndef _Included_lecture_one_jninative_HelloJNI
#define _Included_lecture_one_jninative_HelloJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lecture_one_jninative_HelloJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_lecture_one_jninative_HelloJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
